version: '3.7'

services:
  kursstatistik-api:
    image: $LOCAL_IMAGE_ID
    environment:
      SERVICE_PUBLISH: '/api/kursstatistik'
      SERVER_PORT: 3000
      KURSSTATISTIK_API_KEYS_0: '?name=test&apiKey=1234&scope=read'
      LOGGING_ACCESS_LOG: 'true'

  kursstatistik-integration:
    build: ./test/integration
    depends_on:
      - kursstatistik-api
